export enum JwtEnvNames {
    JWT_SECRET = "JWT_SECRET",
}

export enum EmailEnvNames {
    EMAIL_HOST = "EMAIL_HOST",
    EMAIL_USERNAME = "EMAIL_USERNAME",
    EMAIL_PASSWORD = "EMAIL_PASSWORD",
}

export enum ConfigEnvNames {
    FRONTEND_URL = "FRONTEND_URL",
}

export enum OAuthDiscordEnvNames {
    DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
    DISCORD_CLIENT_SECRET = "DISCORD_CLIENT_SECRET",
    DISCORD_CALLBACK_URL = "DISCORD_CALLBACK_URL",
}

export enum OAuthGoogleEnvNames {
    GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
    GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
    GOOGLE_CALLBACK_URL = "GOOGLE_CALLBACK_URL",
}

export enum OAuthFacebookEnvNames {
    FACEBOOK_CLIENT_ID = "FACEBOOK_CLIENT_ID",
    FACEBOOK_CLIENT_SECRET = "FACEBOOK_CLIENT_SECRET",
    FACEBOOK_CALLBACK_URL = "FACEBOOK_CALLBACK_URL",
}

export enum OAuthGithubEnvNames {
    GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID",
    GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET",
    GITHUB_CALLBACK_URL = "GITHUB_CALLBACK_URL",
}
